### ISSUE TITLE
Getting Time out when starting hub on a machine which is behind a proxy server 

### ISSUE THREAD

**Issue by akash1233** [groupon/Selenium-Grid-Extras#104]
Getting Time out when starting hub on a machine which is behind a proxy server 

Stating the hub with the following command : java -jar SeleniumGridExtras-1.7.1-SNAPSHOT-jar-with-dependencies.jar
getting the following error : 
org.dom4j.DocumentException: Connection timed out: connect Nested exception: Connection timed out: connect
        at org.dom4j.io.SAXReader.read(SAXReader.java:484)
        at org.dom4j.io.SAXReader.read(SAXReader.java:291)
        at com.groupon.seleniumgridextras.downloader.webdriverreleasemanager.WebDriverReleaseManager.<init>(WebDriverReleaseManager.java:52)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.loadWebDriverReleaseManager(RuntimeConfig.java:85)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.getReleaseManager(RuntimeConfig.java:73)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.setDriverAutoUpdater(FirstTimeRunConfig.java:216)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.customiseConfig(FirstTimeRunConfig.java:83)
        at com.groupon.seleniumgridextras.config.Config.initilizedFromUserInput(Config.java:211)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfig.java:133)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:68)
Nested exception:
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)

**Comment by nvonop** [comment]
I am seeing the same issue too. I have tried setting http.proxyHost and http.proxyPort but this didn't fix the problem.

**Comment by ravishan** [comment]
me too faced this problem. i think the http://selenium-release.storage.googleapis.com/ and http://chromedriver.storage.googleapis.com/LATEST_RELEASE should be given as https

**Comment by smccarthy** [comment]
@ravishan @akash1233 Is this issue fixed, now that the PR for using https has been merged in, and a new release has been released?

**Comment by smccarthy** [comment]
Closing this issue as there was no response in awhile. If its still an issue, please post back and we can reopen it.

Also, I saw that you can use an http and https proxy with selenium grid extras via :

 "C:\Program Files\Java\jdk1.7.0_79\bin\java.exe" -Dhttp.proxyHost=yourproxy.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=yourproxy.com -Dhttps.proxyPort=8080 -cp "C:\selenium_ex/SeleniumGridExtras-jar-with-dependencies.jar;C:\selenium_ex/all-node-extensions-0.6.jar" -jar "C:\selenium_ex/SeleniumGridExtras-jar-with-dependencies.jar"

I am not sure if that helps or not, but maybe?

**Comment by thafsouth96** [comment]
Hi, 
I am having the same issue ! 
Need some help :)
