### ISSUE TITLE
Not working with regular Selenium Hub

### ISSUE THREAD

**Issue by bbhenry** [groupon/Selenium-Grid-Extras#131]
I spin up Grid-extra node on a Windows machine and have register to a regular MAC selenium hub, but it gave me error like this on the hub:

```
2015-06-22 15:59:32.323:WARN:osjs.ServletHandler:/grid/register
java.security.InvalidParameterException: Error: com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:434)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:86)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
	at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
	at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
	at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
	at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
	at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
	at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)
```

But it was totally fine if I use Grid-Extra as the hub on my MAC. Can't I not use regular hub with Grid-Extra?

**Comment by chdavi** [comment]
Do you have the SetupTeardownProxy on the class path of the regular selenium hub?  

That is the default proxy for the Selenium Grid Extras nodes and all the hub needs the classes for all the nodes on its class path.

**Comment by bbhenry** [comment]
I didn't find instruction on how to set the SetupTeardownProxy on the class path of the regular Selenium hub, can you point me to the right direction?

**Comment by rgonalo** [comment]
If you have a regular hub, remove the proxy line in the node config file (node_5555.json) and the hub will use default BaseRemoteProxy instead of SetupTeardownProxy.

**Comment by bbhenry** [comment]
@rgonalo Thanks, that worked. Do you know if by doing this will take away any features on the node side?

**Comment by chdavi** [comment]
It will take away most of the functions on the node side. The SetupTearDownProxy is responsible for starting videos, rebooting the node, and the startup/teardown functions that keep the grid more stable.  

By changing the proxy, you are pretty much just spinning up a regular selenium node. If you want to keep the Selenium Grid Extras functionality you need to start the hub with the classes available.

To change the class path you use the standard java syntax. Take a look at the testGetWindowsHubCommand test in the [StartGridTest.java](
https://github.com/groupon/Selenium-Grid-Extras/blob/55a8fb1974babbda934700f4f4127c8f51789466/SeleniumGridExtras/src/test/java/com/groupon/seleniumgridextras/StartGridTest.java) 

Also, keep in mind if you want the configuration file management, you really need the Selenium Grid Extras endpoints running on the hub so the nodes can update/pull their configuration files.

**Comment by bbhenry** [comment]
I was hoping I can use the official docker images to build the Grid with some external Windows VM running the Grid Extra Nodes. Guess I'll have to build custom containers for the Hub now. https://registry.hub.docker.com/repos/selenium/
