### ISSUE TITLE
Video serving causes Existing connection forcibly closed by the remote host.

### ISSUE THREAD

**Issue by chapmanc** [groupon/Selenium-Grid-Extras#135]
30 Jun 2015 12:25:20 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
30 Jun 2015 12:25:20 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4 does exist, responding with 404
30 Jun 2015 12:25:31 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
30 Jun 2015 12:25:31 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4 does exist, responding with 404
30 Jun 2015 12:25:31 [Thread-13] ERROR seleniumgridextras.VideoHttpExecutor  - Something went wrong when serving video file C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at sun.net.httpserver.Request$WriteStream.write(Unknown Source)
	at sun.net.httpserver.ChunkedOutputStream.writeChunk(Unknown Source)
	at sun.net.httpserver.ChunkedOutputStream.write(Unknown Source)
	at sun.net.httpserver.PlaceholderOutputStream.write(Unknown Source)
	at com.groupon.seleniumgridextras.VideoHttpExecutor.handle(VideoHttpExecutor.java:48)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at com.groupon.seleniumgridextras.ParameterFilter.doFilter(ParameterFilter.java:69)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
30 Jun 2015 12:31:31 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
30 Jun 2015 12:31:31 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4 does exist, responding with 404
30 Jun 2015 12:31:31 [Thread-13] ERROR seleniumgridextras.VideoHttpExecutor  - Something went wrong when serving video file C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at sun.net.httpserver.Request$WriteStream.write(Unknown Source)
	at sun.net.httpserver.ChunkedOutputStream.writeChunk(Unknown Source)
	at sun.net.httpserver.ChunkedOutputStream.write(Unknown Source)
	at sun.net.httpserver.PlaceholderOutputStream.write(Unknown Source)
	at com.groupon.seleniumgridextras.VideoHttpExecutor.handle(VideoHttpExecutor.java:48)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at com.groupon.seleniumgridextras.ParameterFilter.doFilter(ParameterFilter.java:69)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
30 Jun 2015 12:31:31 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
30 Jun 2015 12:31:31 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4 does exist, responding with 404
30 Jun 2015 12:31:54 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
30 Jun 2015 12:31:54 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4 does exist, responding with 404
30 Jun 2015 12:31:54 [Thread-13] ERROR seleniumgridextras.VideoHttpExecutor  - Something went wrong when serving video file C:\Users\Administrator\Desktop\selenium_grid_2\video_output\1730029c-0f23-4f10-b1a6-1837d9c08bec.mp4
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(Unknown Source)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.write(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
	at sun.net.httpserver.Request$WriteStream.write(Unknown Source)
	at sun.net.httpserver.ChunkedOutputStream.writeChunk(Unknown Source)
	at sun.net.httpserver.ChunkedOutputStream.write(Unknown Source)
	at sun.net.httpserver.PlaceholderOutputStream.write(Unknown Source)
	at com.groupon.seleniumgridextras.VideoHttpExecutor.handle(VideoHttpExecutor.java:48)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at com.groupon.seleniumgridextras.ParameterFilter.doFilter(ParameterFilter.java:69)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
	at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by chapmanc** [comment]
File plays correctly (on VLC not on WMP) when I remote into the machine but accessing the video from the :3000 page results in the following error.

**Comment by chapmanc** [comment]
Tracked this down to not working with chrome.

**Comment by smccarthy** [comment]
Thanks for that typo on SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/VideoHttpExecutor.java:38  . I updated it to be "200" instead of "404". It already said the file exists though.

**Comment by chapmanc** [comment]
That's fair enough @smccarthy.  The issue is definitely related to the size of the videos. I have gotten around it by right clicking->save as. This allows me to at least download and watch the video. Streaming the video doesn't work on all browsers.
