### ISSUE TITLE
Grid unstable when scaling up

### ISSUE THREAD

**Issue by levisiebens** [groupon/Selenium-Grid-Extras#148]
I've run into an issue when I've tried to scale up my grid with a relatively low number of machines.  My configuration is a Grid Hub running on one machine, with 5 VMs (registered as nodes) on a separate machine. The nodes are split across two different hard drives (minimizing some of the disk thrashing that can occur with VMs) and the VMs tend to run relatively well (1CPU, 2 gigs of ram, 40gig of space running Windows 8). However, when I fully load the grid with tests, I will get intermittent exceptions when I instantiate the remote web driver. It seems like this occurs if it takes more then 30 seconds to create the remote web driver connection. The error is listed below:

Exception Message: The error did not contain a message.

Call Stack:
Void UnpackAndThrowOnError(OpenQA.Selenium.Remote.Response)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)

Server Log Line Related:
"external_key": "Session be97c3ba-5f38-4a1c-a9bb-5474e708a1d3, did not get an external key after 120 seconds.\nMore info: {external_key\u003dNot Yet Assigned, port\u003d5555, requested_capabilities\u003d{nativeEvents\u003dtrue, ie.ensureCleanSession\u003dtrue, enablePersistentHover\u003dtrue, browserName\u003dinternet explorer, version\u003d, platform\u003dWINDOWS, unexpectedAlertBehaviour\u003ddismiss}, host\u003d192.168.60.139, internal_key\u003dbe97c3ba-5f38-4a1c-a9bb-5474e708a1d3, timestamp\u003d2015-07-31 13:23:48.759}",

I originally thought this was a configuration issue with my network or hardware, but after moving the machines to just be a standard selenium grid, I did not see the same issue. Also of note, it looks like the error is coming from SessionHistoryCallable.java.

**Comment by smccarthy** [comment]
@levisiebens  I wonder if this is a selenium-grid-extras issue, or a selenium issue. Are you still using selenium grid extras ? Do you still see this issue? What version of SeleniumGridExtras? Also, where did you see that it could be from SessionHistoryCallable.java ? 

Thanks.

**Comment by nvonop** [comment]
I am seeing the same issue.  Log entry below.  Selenium version is 3.3.1, Grid Extras is 1.12.12.

31 May 2017 09:44:18 [pool-1-thread-9848] ERROR threads.SessionHistoryCallable  - Session c1e55766-afb5-47ec-be89-9909c0976c0f, did not get an external key after 120 seconds.
More info: {external_key=Not Yet Assigned, port=5555, host=10.18.13.247, internal_key=c1e55766-afb5-47ec-be89-9909c0976c0f, timestamp=2017-05-31 09:44:18.589}
31 May 2017 09:44:18 [pool-1-thread-9848] INFO  loggers.SessionHistoryLog  - Registering new session to file C:\Selenium\Grid\log\session_logs\10.18.13.247_31_05_2017.log
31 May 2017 09:44:18 [pool-1-thread-9848] INFO  threads.SessionHistoryCallable  - Notifying Remote Grid Extras node of new session with http://10.18.13.247:3000/grid_status?session=Session+c1e55766-afb5-47ec-be89-9909c0976c0f%2C+did+not+get+an+external+key+after+120+seconds.

**Comment by smccarthy** [comment]
@nvonop Do you know if you get this error without using grid extras? I am really unsure how to solve this one if it is a grid extras issue.

**Comment by nvonop** [comment]
@smccarthy sorry for the slow response, I haven't had a chance to verify this yet.  leave it with me.  It isn't forgotten (or ignored)!
