### ISSUE TITLE
Node dies in the middle of the test run due to "Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by Eriten** [groupon/Selenium-Grid-Extras#169]
I've been facing this problem numerously times and it seems to happen randomly, but is guarantee to happen to a couple nodes when many tests are ran over 20 nodes for more than 6 hours of test run continuously. The blocks below show the exception messages I've found in multiple log files. Please look at this asap as this might be a blocking issue for others as well!

The following is the exception message from the cron log
```
bash: cannot set terminal process group (7886): Inappropriate ioctl for device                                                          
bash: no job control in this shell
```

The following is the exception log from node_5555.log -
```
1:01:14.011 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Executing: [switch to window: CDwindow-29954342-DFF2-4E98-BEEC-12CBB142E38E])
01:01:14.043 WARN [14] org.openqa.selenium.remote.server.DriverServlet - Exception thrown
org.openqa.selenium.remote.SessionNotFoundException: no such session
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.13.0-36-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'ip-10-25-10-23', ip: '10.25.10.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_65'
Session ID: 7c6d61abddc11e5ace97cd6249fd6e2c
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.Rb1jqN}, rotatable=false, locationContextEnabled=true, version=40.0.2214.91, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:895)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTargetLocator.window(EventFiringWebDriver.java:594)
        at org.openqa.selenium.remote.server.handler.SwitchToWindow.call(SwitchToWindow.java:43)
        at org.openqa.selenium.remote.server.handler.SwitchToWindow.call(SwitchToWindow.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
01:01:14.043 WARN [14] org.openqa.selenium.remote.server.DriverServlet - Exception: no such session
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.13.0-36-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 32 milliseconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'ip-10-25-10-23', ip: '10.25.10.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_65'
Session ID: 7c6d61abddc11e5ace97cd6249fd6e2c
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.Rb1jqN}, rotatable=false, locationContextEnabled=true, version=40.0.2214.91, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
01:04:35.004 INFO [18] org.openqa.selenium.remote.server.DriverServlet - Session 902e3f8b-f09d-4f03-8355-c27428d36468 deleted due to client timeout
```

**Comment by smccarthy** [comment]
I am not sure if it will help, but I see your chromedriver is version 2.9, but the notes for 2.9 ( https://chromedriver.storage.googleapis.com/2.9/notes.txt ), says it only supports up to Chrome 34. You are using Chrome 40. I actually don't think that will help, but it is just something to note.

**Comment by Eriten** [comment]
That is a good point, @smccarthy ! I'll try to update my chrome driver and give it a shot! Thanks!

**Comment by smccarthy** [comment]
@Eriten Did upgrading chromedriver version help you ?

**Comment by Eriten** [comment]
Sorry for the late reply. The functionality was working :)

**Comment by smccarthy** [comment]
Closing as issue is fixed.
