### ISSUE TITLE
Documentation on how to create a release

### ISSUE THREAD

**Issue by lucacri** [groupon/Selenium-Grid-Extras#175]
Hello,
this project is awesome (when it works) but unfortunately it's lacking documentation. I'm trying to create a new release jar file from the source code because there were some merges that are not in the available release yet, but I can't figure out how to do it.

I'm using maven (i guess), but it gives some errors in the tests and then it gets stuck asking me what kind of role it should have:

```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.046 sec <<< FAILURE!
testGetBackgroundStartCommandForNode(com.groupon.seleniumgridextras.grid.GridStarterTest)  Time elapsed: 0.01 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<start []foo.bat> but was:<start [/MIN ]foo.bat>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.groupon.seleniumgridextras.grid.GridStarterTest.testGetBackgroundStartCommandForNode(GridStarterTest.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.groupon.seleniumgridextras.grid.proxies.sessions.threads.SetupTeardownProxyTest




We noticed this is a first time running, we will ask some configuration settings




What is the default Role of this computer? (1 - node | 2 - hub | 3 - hub & node)
Default Value: 1
```

Any idea of how to proceed?

**Comment by smccarthy** [comment]
I think this is from a merge recently. It's one (or two) of the tests that are causing this I think. I can Ignore those two tests once I figure out exactly which tests are doing this.

**Comment by smccarthy** [comment]
@lucacri If still interested , is this still broke for you? Things should hopefully be better now.

**Comment by lucacri** [comment]
@smccarthy sorry, i'm not using selenium grid extras anymore..

**Comment by smccarthy** [comment]
Closing. If still broke for other people, please open a new issue.

Thank you.
