### ISSUE TITLE
Headless Mode?

### ISSUE THREAD

**Issue by strowi** [groupon/Selenium-Grid-Extras#189]
Hi,

great work so far! I have been testing this on my local machine and it seems to be working very nice.

But now i wanted to deploy this on a couple of servers and i cant seem to get this running in headless mode...?

```
~>xvfb-run java -Djava.awt.headless=true SeleniumExtrasGrid.jar
...
You can modify this file directly to tweak more options
Y DeleteOldLogsTask - /log_delete - Delete logs older than X Days. X is define in the config.json
N MoveMouse
Y RebootNode - /reboot - Restart the host node
Y VideoRecorder - /video - Starts and stops video recording
Y KillAllIE - /kill_ie - Executes os level kill command on all instance of Internet Explorer
Y KillAllFirefox - /kill_firefox - Executes os level kill command on all instance of Firefox
Y KillAllChrome - /kill_chrome - Executes os level kill command on all instance of Google Chrome
Y KillAllSafari - /kill_safari - Executes os level kill command on all instance of Safari
Y SetAutoLogonUser - /user_auto_logon - Sets a user to automatically logon into system post reboot
Y GetProcesses - /ps - Gets a list of currently running processes
Y KillPid - /kill_pid - Kills a given process id
Y Netstat - /netstat - Returns a system call for all ports. Use /port_info to get parsed details
Y Screenshot - /screenshot - Take a full OS screen Screen Shot of the node
Y ExposeDirectory - /dir - Gives accesses to a shared directory, user has access to put files into it and get files from it. Directory deleted on restart.
Y StartGrid - /start_grid - Starts an instance of Selenium Grid Hub or NodeConfig
Y GetInfoForPort - /port_info - Returns parsed information on a PID occupying a given port
Y GridStatus - /grid_status - Returns status of the Selenium Grid hub/node. If currently running and what is the PID
Y KillAllByName - /kill_all_by_name - Executes os level kill command on a given PID name
Y StopGrid - /stop_grid - Stops grid or node process
Y GetConfig - /config - Returns JSON view of the full configuration of the Selenium Grid Extras
Y StopGridExtras - /stop_extras - Shuts down Grid Extras service
Y IEProtectedMode - /ie_protected_mode - Changes protected mode for Internet Explorer on/off. No param for current status
Y IEMixedContent - /ie_mixed_content - Changes mixed content for Internet Explorer on/off. No param for current status
Y SystemInfo - /system - Returns system details about the current node
Y GetNodeConfig - /get_node_config - Provides the grid node config from central location
Y UpdateNodeConfig - /update_node_config - Send the current config to the central location to be stored
Y AutoUpgradeDrivers - /auto_upgrade_webdriver - Automatically checks the latest versions of all drivers and upgrades the current config to use them
Y DownloadWebdriver - /download_webdriver - Downloads a version of WebDriver jar to local machine
Y DownloadIEDriver - /download_iedriver - Downloads a version of IEDriver.exe to local machine
Y DownloadChromeDriver - /download_chromedriver - Downloads a version of ChromeDriver to local machine
Y SessionHistory - /session_history - Displays the threads of test session on all nodes or per node basis
N UpgradeGridExtrasTask
Attempting to start Grid Hubs

Selenium Grid Extras has been started!
Navigate to http://172.17.0.2:3000 for more details
java.awt.AWTException: headless environment
	at java.awt.Robot.<init>(Robot.java:91)
	at com.groupon.seleniumgridextras.utilities.ScreenshotUtility.getFullScreenshot(ScreenshotUtility.java:22)
	at com.groupon.seleniumgridextras.utilities.ScreenshotUtility.getResizedScreenshot(ScreenshotUtility.java:29)
	at com.groupon.seleniumgridextras.utilities.ScreenshotUtility.getResizedScreenshotAsBase64String(ScreenshotUtility.java:51)
	at com.groupon.seleniumgridextras.homepage.HtmlNodeRenderer.getScreenshot(HtmlNodeRenderer.java:286)
	at com.groupon.seleniumgridextras.homepage.HtmlNodeRenderer.buildScreenshotBillboard(HtmlNodeRenderer.java:319)
	at com.groupon.seleniumgridextras.homepage.HtmlNodeRenderer.getFullHtml(HtmlNodeRenderer.java:45)
	at com.groupon.seleniumgridextras.homepage.HtmlRenderer.toString(HtmlRenderer.java:71)
	at com.groupon.seleniumgridextras.SeleniumGridExtras$3.execute(SeleniumGridExtras.java:125)
	at com.groupon.seleniumgridextras.HtmlHttpExecutor.handle(HtmlHttpExecutor.java:56)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at com.groupon.seleniumgridextras.ParameterFilter.doFilter(ParameterFilter.java:69)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)
```

regards,
strowi

**Comment by strowi** [comment]
Actually.. scratch that... my bad. I had onliny jre-headless installed. With the normal jre it works fine running via xvfb.

regards,
strowi
