### ISSUE TITLE
Can't specify grid-extras management port (default = 3000)

### ISSUE THREAD

**Issue by tk8817** [groupon/Selenium-Grid-Extras#204]
Hi Folks,

While I can specify the selenium bind port (5555, 5556, etc...) I cannot find anywhere to specify the grid-extras management port and thus it fails to boot saying the port is already in use. 

```
C02Q74VEG8WN:grid jcommu$ ./start_grid_extras.sh 
Exception in thread "main" java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:77)
C02Q74VEG8WN:grid jcommu$ 
```

We are trying to do some crazy mac kung-fu where we create multiple user accounts so we can connect multiple safari instances to our grid using the same machine. Each Safari install gets its own profile, so they don't interfere with each other :)

**Comment by smccarthy** [comment]
I like this idea, and I don't think it would be too hard to implement. PRs welcome! I am not sure I will have time in the next few weeks or months to work on this.

**Comment by drptbl** [comment]
:+1:

**Comment by smccarthy** [comment]
https://github.com/groupon/Selenium-Grid-Extras/pull/258

@drptbl @tk8817

**Comment by smccarthy** [comment]
Merged in. It will be in the next release (no ETA, but maybe in a week or so). Feel free to pull master and do a `mvn clean install -DskipTests` to get the latest jar file.

**Comment by interhealth** [comment]
How do I specify the default port? 
I'm using WDIO  v4.2.16

**Comment by smccarthy** [comment]
It's in the selenium grid extras config file
