### ISSUE TITLE
Unable to set phantomjs capability for a node

### ISSUE THREAD

**Issue by Zloy** [groupon/Selenium-Grid-Extras#212]
I use selenium grid extras of version 1.11.8
I cannot see phantomjs browser option in setting up wizard. So, how can I add this capability to node_5555.json config?

**Comment by Zloy** [comment]
I tried to declare phantomjs such way
```
{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 3,
      "version": "42",
      "platform": "WINDOWS"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "phantomjs",
      "maxInstances": 3,
      "version": "",
      "platform": "WINDOWS"
    }
  ],
  "__WARNING__": "THIS FILE IS AUTOMATICA...
  ...
}

```


but starting jar failed
```
C:\Selenium.extras>java -jar SeleniumGridExtras-1.11.8-SNAPSHOT-jar-with-dependencies.jar
Checking central Config repository for sele-node-zhant node's config from http://qa1:3000/get_node_config?node=sele-node-1 . (Timeout set to 5000ms) 
[node_5555.json, exit_code, error, selenium_grid_extras_config.json, out]
Updated 'node_5555.json' from central config repository
Updated 'selenium_grid_extras_config.json' from central config repository
Exception in thread "main" java.lang.NullPointerException
        at com.groupon.seleniumgridextras.config.capabilities.Capability.getCapabilityFor(Capability.java:72)
        at com.groupon.seleniumgridextras.config.GridNode.loadFromFile(GridNode.java:57)
        at com.groupon.seleniumgridextras.config.Config.loadNodeClasses(Config.java:115)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfig.java:146)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:72)
```

**Comment by smccarthy** [comment]
@Zloy Can you try 1.12.2 ? I think there was a PR related to PhantomJS that went into this release.

Please post back if it is fixed, or if it is still broke.

Thank you!

**Comment by Zloy** [comment]
@smccarthy
Sorry, I cannot try that now as we've switched to Selenium docker

**Comment by smccarthy** [comment]
Thanks for the quick reply. I will close this issue and if someone still sees an issue, they can open a new issue for it.
