### ISSUE TITLE
Make a release fat jar available consistently

### ISSUE THREAD

**Issue by dave-miles** [groupon/Selenium-Grid-Extras#222]
We started using grid extras at release 1.11.8 which had a fat jar available for download. We'd like to upgrade to release 1.12.1 but no fat jar is available. Would it be possible to always make a fat jar available per release?

**Comment by dave-miles** [comment]
Downloading the 1.12.1 source archive and running the following gives the fat jar:
```
mvn clean package -Dmaven.test.skip=true versions:set -DnewVersion=1.12.1
```

If I don't skip the unit tests I get:
```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.193 sec <<< FAILURE!
testChromeDriverDString(com.groupon.seleniumgridextras.grid.GridStarterTest)  Time elapsed: 0.038 sec  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at com.groupon.seleniumgridextras.grid.GridStarterTest.testChromeDriverDString(GridStarterTest.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by smccarthy** [comment]
Sorry, this was my first time with the release. I did it incorrectly. I will try and figure out how to include the "fat" jar along with the release. If someone else knows how to, please let me know. Thank you.

**Comment by smccarthy** [comment]
I also ran all the tests and they passed for me. I did just commit a fix for the non-windows users.

**Comment by smccarthy** [comment]
Oh, you are on windows. Can you try to edit the test, to print out : GridStarter.getChromeDriverExecutionPathParam() to see what it equals ? I will try and get it working on a Windows machine to see, but not sure how long it will take me. @dave-miles

**Comment by Yukonjess101** [comment]
We're using this as well and would also like to move to the next version.  Do you have an idea when the jar might be available?

**Comment by smccarthy** [comment]
@Yukonjess101 @dave-miles 
https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.2

Please try that one out. 1.12.2 fixes a non-windows first time config problem.

**Comment by Yukonjess101** [comment]
Looks good, Thanks!

**Comment by smccarthy** [comment]
@dave-miles I tried to get this working on Windows, but it seems Xuggle (the library we use for video recording) isn't available anymore, so I can't compile the project. I will try and make a new branch with video pulled out, just to test this chromedriver test.

**Comment by smccarthy** [comment]
@dave-miles I fixed the test and commited it to master. Closing this issue.
