### ISSUE TITLE
exception during config wizard

### ISSUE THREAD

**Issue by martineez** [groupon/Selenium-Grid-Extras#272]
Hi,
Version 1.12.5

There is an exception thrown in configuration wizard after detecting IE version
(in version 1.12.4 it is fine)
`Will this node run 'InternetExplorer' (1-yes/0-no)
Default Value: 0
1
'1' was set as your value
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/WinReg
        at com.groupon.seleniumgridextras.browser.BrowserVersionDetector.getIEVersion(BrowserVersionDetector.java:135)
        at com.groupon.seleniumgridextras.browser.BrowserVersionDetector.guessBrowserVersion(BrowserVersionDetector.java:117)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.getCapabilitiesFromUser(FirstTimeRunConfig.java:413)
        at com.groupon.seleniumgridextras.config.FirstTimeRunConfig.customiseConfig(FirstTimeRunConfig.java:88)
        at com.groupon.seleniumgridextras.config.Config.initilizedFromUserInput(Config.java:248)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfig.java:139)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:70)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.platform.win32.WinReg
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more`

**Comment by smccarthy** [comment]
Thanks for reporting this. I can look at this later today

**Comment by rhehl** [comment]
@smccarthy removing "<dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>4.1.0</version>
	</dependency>"

seem's to be the problem, after adding this again it works for me

P.S.: Which IDE do you use? I'm not able to use Eclipse with this Project

**Comment by smccarthy** [comment]
@rhehl I use Eclipse. I'll add that dependency back in a bit and retry and make a new release. Thanks for finding this !

Why can't you use Eclipse ?

**Comment by rhehl** [comment]
@smccarthy 
![seleniumgridextras_src_main_java_com_groupon_seleniumg](https://cloud.githubusercontent.com/assets/7577984/19694232/c1e6596a-9ade-11e6-8cab-d848b7023c5c.png)

**Comment by smccarthy** [comment]
@rhehl What version of java are you using? You might need at least JDK 7 or maybe even 8 (not sure). I use jdk 8. If you scroll down in the package explorer on the left you can see

**Comment by rhehl** [comment]
@smccarthy you where right, i've installed on my system 1.8. but choosen was for this project 1.5 :/ thx

**Comment by smccarthy** [comment]
@martineez @rhehl https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v1.12.6

**Comment by smccarthy** [comment]
Closing as this is fixed. If still an issue, please comment back. Thank you.
