### ISSUE TITLE
IllegalStateException When Trying To Register The Node To Hub

### ISSUE THREAD

**Issue by Gowritharan** [groupon/Selenium-Grid-Extras#300]
Hi I am wondering if I could get some assistance on this issue I am facing or ways to debug this problem.  I have been using Hub/Node setup for awhile now and started noticing my Mac nodes started randomly disconnecting from the Hub randomly.  I updated my Mac nodes to version 1.12.7 and now they are failing trying to register to the hub.  One odd thing is that the nodes are able to send the Hub the config files. 

The logs are not too helpful and I am not sure how to start in debug mode:

> 00:21:08.248 INFO - Registering the node to the hub: http://hub01.qatest.sc-core.net:4444/grid/register
> 00:21:08.251 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error
> 00:21:13.254 INFO - Registering the node to the hub: http://hub01.qatest.sc-core.net:4444/grid/register
> 00:21:13.259 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error

The error I am getting on the browser when I manually try to do it:

> HTTP ERROR: 500
> Problem accessing /grid/register. Reason:  java.lang.IllegalStateException: Not a JSON Object: null

My node_5555.json file looks like this:

> {
>   "capabilities": [
>     {
>       "seleniumProtocol": "WebDriver",
>       "browserName": "firefox",
>       "maxInstances": 3,
>       "version": "45",
>       "platform": "MAC"
>     },
>     {
>       "seleniumProtocol": "WebDriver",
>       "browserName": "chrome",
>       "maxInstances": 3,
>       "version": "55",
>       "platform": "MAC"
>     },
>     {
>       "seleniumProtocol": "WebDriver",
>       "browserName": "safari",
>       "maxInstances": 3,
>       "version": "",
>       "platform": "MAC"
>     }
>   ],
>   "loadedFromFile": "node_5555.json",
>   "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
>   "maxSession": 3,
>   "port": 5555,
>   "register": true,
>   "unregisterIfStillDownAfter": 10000,
>   "hubPort": 4444,
>   "hubHost": "hub01.qatest.sc-core.net",
>   "registerCycle": 5000,
>   "nodeStatusCheckTimeout": 10000,
>   "downPollingLimit": 0
> }

Any help would be much appreciated.

**Comment by Gowritharan** [comment]
Update: I was able to start server/node in DEBUG

SERVER CONSOLE OUTPUT:

> [qtp1858609436-26] WARN org.seleniumhq.jetty9.servlet.ServletHandler - /grid/register
> java.lang.NullPointerException
> 	at org.openqa.grid.common.RegistrationRequest.getNewInstance(RegistrationRequest.java:276)
> 	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:75)
> 	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:60)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
> 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
> 	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
> 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
> 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
> 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
> 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
> 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
> 	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
> 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
> 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
> 	at java.lang.Thread.run(Thread.java:745)

SERVER hub_4444.log:

> DEBUG [19] org.openqa.grid.web.servlet.RegistrationServlet - getting the following registration request :
> {"class":"org.openqa.grid.common.RegistrationRequest","configuration":{"unregisterIfStillDownAfter":10000,"role":"node","log":"log\\node_5555.log","remoteHost":"http://10.44.24.34:5555","nodeStatusCheckTimeout":10000,"hubHost":"hub01.qatest.sc-core.net","hubPort":4444,"downPollingLimit":0,"nodeConfig":"node_5555.json","url":"http://10.44.24.34:5555","timeout":3600000,"proxy":"com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy","port":5555,"friendlyHostName":"DESKTOP-7AFBN2C","host":"10.44.24.34","browserTimeout":3600000,"maxSession":3,"registerCycle":5000,"register":true},
> "capabilities":[{"browserName":"firefox","seleniumProtocol":"WebDriver","maxInstances":1,"version":"47","platform":"WIN10"},{"browserName":"internet explorer","seleniumProtocol":"WebDriver","maxInstances":1,"version":"11","platform":"WIN10"},{"browserName":"MicrosoftEdge","seleniumProtocol":"WebDriver","maxInstances":1,"version":"","platform":"WIN10"},{"browserName":"chrome","seleniumProtocol":"WebDriver","maxInstances":1,"version":"55","platform":"WIN10"}]}

**Comment by sandeepjain1987** [comment]
Did you find a solution ?

**Comment by kyleshrader** [comment]
It appears removing the proxy fixes the issue. This implies that the hub needs to have this resource, so you likely need to run the hub using SeleniumGridExtras as well.
