### ISSUE TITLE
Selenium 3.1 is wrongly recognized as Selenium 2

### ISSUE THREAD

**Issue by zsucic** [groupon/Selenium-Grid-Extras#309]
I think that this line in StartGrid.java:
boolean isSelenium3 = RuntimeConfig.getConfig().getWebdriver().getVersion().startsWith("3.0");

should actually be:
boolean isSelenium3 = RuntimeConfig.getConfig().getWebdriver().getVersion().startsWith("3.");

because now with webdriver version 3.1 out, and automatic webdriver update, the SGE stops converting the node config file to match the Selenium 3 version...
The issue is then visible in the log files as:

 command: /usr/lib/jvm/java-8-oracle/jre/bin/java -Dwebdriver.chrome.driver=/tmp/webdriver/chromedriver/chromedriver_2.27_64bit -Dwebdriver.gecko.driver=/tmp/webdriver/geckodriver/geckodriver_0.14.0 -cp /home/user/Desktop/SeleniumGrid/SeleniumGridExtras-1.12.10-SNAPSHOT-jar-with-dependencies.jar:/tmp/webdriver/3.1.0.jar org.openqa.grid.selenium.GridLauncherV3 -role node -nodeConfig node_5555.json -log log/node_5555.log  
 exit code: 1 
 standard error: 
 Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationException: Error with the JSON of the config : Deprecated -nodeConfig file encountered. Please update the file to work with Selenium 3. See https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json for more details.
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:444)
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:421)
	at org.openqa.grid.selenium.GridLauncherV3$3.setConfiguration(GridLauncherV3.java:271)
	at org.openqa.grid.selenium.GridLauncherV3.buildLauncher(GridLauncherV3.java:155)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:75)
Caused by: org.openqa.grid.common.exception.GridConfigurationException: Deprecated -nodeConfig file encountered. Please update the file to work with Selenium 3. See https://github.com/SeleniumHQ/selenium/wiki/Grid2#configuring-the-nodes-by-json for more details.
	at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.loadFromJSON(GridNodeConfiguration.java:436)
	... 4 more

Temporary workaround  is to disable the automatic driver update and set the webdriver version to below 3.1, e.g. 3.0.0

**Comment by mstankovic86** [comment]
+1

Workaround: set auto update drivers to 0, and use webdriver 3.0.1.

**Comment by travisneedham** [comment]
+1

Thanks for the workaround, it's working great for me!

**Comment by smccarthy** [comment]
Thank you ! I will make the fix now

**Comment by smccarthy** [comment]
Fixed it here : https://github.com/groupon/Selenium-Grid-Extras/commit/a6c3cc29ff07d1f7ff889c6b3a132fc3472d34d4

**Comment by smccarthy** [comment]
I am prepping for a release, but not sure how much testing I can do anytime soon. @zsucic @travisneedham @mstankovic86 If you can grab the latest to test with, that would be helpful.

**Comment by travisneedham** [comment]
I can probably do it on Monday.  I need my environment to be stable this weekend.

**Comment by zsucic** [comment]
Same here...

**Comment by akaguny** [comment]
When y do bugfix?

**Comment by mstankovic86** [comment]
did someone test it?

**Comment by smattt** [comment]
I'd be happy to test it with my small configuration (Hub & 3 Node VMs) if there are test bits available.

**Comment by akaguny** [comment]
@mstankovic86 when i try build github version app with maven build failed and don`t build
```

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Selenium Grid Extras 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] SeleniumGridExtras ................................. FAILURE [ 41.067 s]
[INFO] Selenium Grid Extras ............................... SUCCESS [  0.002 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.280 s
[INFO] Finished at: 2017-02-24T12:21:12+03:00
[INFO] Final Memory: 31M/358M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project SeleniumGridExtras: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/alexey/IdeaProjects/Selenium-Grid-Extras/SeleniumGridExtras/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] Build failures were ignored.

```

**Comment by smattt** [comment]
Binaries look to be posted (thanks devs!) but GitHub is choking on file downloads atm.

**Comment by smccarthy** [comment]
You're welcome! Please let me know if this is fixed. I tested it and I believe its fixed, but would like to here from someone who had the issue.

Thank you

**Comment by zsucic** [comment]
v1.12.11 seems to recognize Selenium version correctly now, however because of this issue:
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
I'm unable to use 3.1 or 3.2 
with 3.0 it seems to work ok so workaround is still valid.

**Comment by smattt** [comment]
My experience matches zsucic, I rolled back to 3.0.1 and all is fine.

**Comment by smccarthy** [comment]
@zsucic @smattt I made the fix in 1.12.12 (for Precondition). I bumped the guava dependency.

**Comment by smattt** [comment]
v1.12.12 is working great for us! Thanks again!

**Comment by travisneedham** [comment]
Same here. v1.12.12 is working great for us! Thank you!

**Comment by mwalton236** [comment]
v1.12.12 worked for me briefly when using webdriver 3.2.0.

but now webdriver 3.3.0 is out, it's not working again. 

As a work around I've set webdriver version to 3.2.0 and disabled auto updating of drivers, this has got my nodes working again for now.

**Comment by beratomi** [comment]
I tried a fresh installation on a Linux VM (ubuntu 14.04) for evaluation purposes and failed with errors like described above. Tried different settings: Autoupdate drivers turned on and off, using webdriver version 3.2.0, setting iedriver to 2.53.1, which works on an older version of selenium-grid-extras.
Nevertheless, installation always stops with following exception:
Download IE Driver Executable 2.53.1
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/tools/ant/taskdefs/Expand : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.groupon.seleniumgridextras.downloader.Unzipper.unzip(Unzipper.java:62)
	at com.groupon.seleniumgridextras.downloader.IEDownloader.download(IEDownloader.java:105)
	at com.groupon.seleniumgridextras.tasks.DownloadIEDriver.execute(DownloadIEDriver.java:117)
	at com.groupon.seleniumgridextras.tasks.DownloadIEDriver.execute(DownloadIEDriver.java:88)
	at com.groupon.seleniumgridextras.tasks.DownloadIEDriver.initialize(DownloadIEDriver.java:153)
	at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:88)

**Comment by sebkap** [comment]
@beratomi 
Try to install newest java for ubuntu. It looks like you try to run jar with older version than it was compiled.

Details: http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

**Comment by beratomi** [comment]
Thx, you made my day :-)
