### ISSUE TITLE
Error 500 when trying to start Appium Android driver

### ISSUE THREAD

**Issue by VivaLosDoyers** [groupon/Selenium-Grid-Extras#323]
I have a grid node hosting Appium connected to my hub.

When I ask the hub to execute an Android test on the node, I get:

```
irb(main):044:0> driver.start_driver
Selenium::WebDriver::Error::ServerError: status code 500
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/default.rb:107:in `request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/bridge.rb:669:in `raw_execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/bridge.rb:647:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/remote/bridge.rb:116:in `status'
	from /usr/local/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/driver_extensions/has_remote_status.rb:25:in `remote_status'
	from /usr/local/lib/ruby/gems/2.4.0/gems/appium_lib-9.3.3/lib/appium_lib/driver.rb:498:in `appium_server_version'
	from /usr/local/lib/ruby/gems/2.4.0/gems/appium_lib-9.3.3/lib/appium_lib/driver.rb:621:in `start_driver'
	from (irb):44
	from /usr/local/bin/irb:11:in `<main>'
```

I suspect the source of this problem is that the Hub is (incorrectly) reporting that the Appium instance is down.
```
==> hub_4444.log <==
15:28:35.367 INFO - Registered a node http://10.10.131.68:4723
15:28:50.380 INFO - Marking the node http://10.10.131.68:4723 as down: cannot reach the node for 1 tries
15:29:05.391 INFO - Unregistering the node http://10.10.131.68:4723 because it's been down for 15011 milliseconds
15:29:05.392 WARN - Cleaning up stale test sessions on the unregistered node http://10.10.131.68:4723
```

However, the Appium instance on the node at http://10.10.131.68:4723 is available, and I can connect to it directly. The node and the hub both do not have any firewall enabled, nor is there a firewall on my network, so I don't think this is a network config problem on my end.

**Comment by smccarthy** [comment]
I haven't looked at appium yet, but are you using selenium 3.3.0 ? or 3.2.0 or ? I have seen a few different reports of people using selenium 3.3.0 and selenium grid extras (having the disconnect/unregister issue). I am not sure if its a grid extras issue or a generic selenium issue. I haven't had the time to dig into this myself.

**Comment by VivaLosDoyers** [comment]
I'm using 3.2.0

 I was actually one of the people that reported this problem with 3.3.0 yesterday, and thanks to your advice I rolled back to 3.2.0 to solve the disconnection problem. 

So I guess this issue with Appium is unrelated?

**Comment by VivaLosDoyers** [comment]
Or perhaps Appium is using 3.3.0 internally? Could that cause a problem like this?

**Comment by scoderp** [comment]
Any luck with this? I occasionally see the same issue launching Selenium tests on a grid.
