### ISSUE TITLE
Selenium Grid Extras fails to start with any version of Gecko driver/Webdriver; NullPointerException.  

### ISSUE THREAD

**Issue by osmolyar** [groupon/Selenium-Grid-Extras#386]
SeleniumGridExtras had been starting fine, but after changing the geckodriver version from 0.19.1 to 0.14.0 in seleniumGridExtrasConfig on the hub (and nodes), it stopped launching, giving the below error:

C:\__NODE__> java -jar "C:\__NODE__\SeleniumGridExtras-1.12.10-SNAPSHOT-jar-with-dependencies.jar"
Checking central Config repository for AT-FIREFOX node's config from http://AT-HUB:3000/get_node_config?node=AT-FIREFOX . (Timeout s
et to 5000ms)
[node_5555.json, exit_code, error, selenium_grid_extras_config.json, out]
Updated 'node_5555.json' from central config repository
Updated 'selenium_grid_extras_config.json' from central config repository
Exception in thread "main" java.lang.NullPointerException
        at com.groupon.seleniumgridextras.config.GridNode.loadFromFile(GridNode.java:128)
        at com.groupon.seleniumgridextras.config.Config.loadNodeClasses(Config.java:119)
        at com.groupon.seleniumgridextras.config.RuntimeConfig.load(RuntimeConfig.java:152)
        at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:70)

The same error occurs even after reverting the geckodriver version to 0.19.1 everywhere.

Currently using Webdriver 3.0.1 (FF version 45) and geckodriver 14.0, because I have been unable to find any more recent combination of versions that will work (url not typing into address bar).  However the above error starting SeleniumGridExtras occurs regardless of the versions used.

**Comment by jasontseu1983** [comment]
I have try using these settings. it is working fine for geckodriver
SeleniumGridExtras v2.0.4
SeleniumGrid 3.11.0
GeckoDriver 0.20.1 64bit
Firefox 64bit

**Comment by osmolyar** [comment]
Jason, thank you very much for the response.  Do you happen to know which version of Firefox 64bit?

**Comment by osmolyar** [comment]
Still not working for me unfortunately with
SeleniumGridExtras v2.0.4
SeleniumGrid 3.11.0
GeckoDriver 0.20.1 64bit
Firefox 60.0  64bit

Output is 
"ERROR: [Object OBJECT]
firefox"

Any suggestions as to how to troubleshoot this or what can be modified to JSON.stringify the error object?

**Comment by osmolyar** [comment]
Any suggestions here?  It seems the same issue is unresolved here https://github.com/groupon/Selenium-Grid-Extras/issues/382  and here http://selenium.10932.n7.nabble.com/Selenium-grid-extras-fails-to-start-NullPointerException-at-com-groupon-seleniumgridextras-confi-td59318.html.

In all cases it works fine with Selenium Standalone server, just not with Grid Extras.
