### ISSUE TITLE
Unable to register node to the hub

### ISSUE THREAD

**Issue by vlemaitre** [groupon/Selenium-Grid-Extras#390]
Hello,

I have a Selenium Grid Extras setup (Hub and Nodes) at version 2.0.1.
Since this morning I get the following errors on my nodes : 
Registering the node to the hub: http://vmrfxv9selsrv:4444/grid/register
11:30:00.603 INFO - Couldn't register this node: Error sending the registration request: The hub responded with 500:Server Error

The connected node list is empty on the Hub grid console.

All my configs file are saved on the hub and retrieved when the node starts.
Here is one of my nodes config file : 

{
  "capabilities": [
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "firefox",
      "maxInstances": 3,
      "version": "57",
      "platform": "WINDOWS"
    },
    {
      "seleniumProtocol": "WebDriver",
      "browserName": "chrome",
      "maxInstances": 3,
      "version": "63",
      "platform": "WINDOWS"
    }
  ],
  "loadedFromFile": "node_5555.json",
  "proxy": "com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy",
  "servlets": [],
  "maxSession": 3,
  "port": 5555,
  "register": true,
  "unregisterIfStillDownAfter": 0,
  "hubPort": 4444,
  "hubHost": "vmrfxv9selsrv",
  "host": "vmrfxv9selnode1",
  "registerCycle": 5000,
  "nodeStatusCheckTimeout": 10000,
  "custom": {},
  "downPollingLimit": 0
}

I was already on the 2.0.1 version for many weeks now without any issue.

The nodes are able to access the hub machine.
The ports are 3000 and 5555 are still accessibles.
The configuration files didn't change...

It seems that the node configs is not accepted by the hub...

Any ideas about this error?

**Comment by vlemaitre** [comment]
Here is the configuration of my Hub : 
![image](https://user-images.githubusercontent.com/17738959/36093678-a61e8a58-0feb-11e8-81d1-bb133c522e95.png)

**Comment by vlemaitre** [comment]
It seems my issue is quite similar to https://github.com/groupon/Selenium-Grid-Extras/issues/389
When I moved on Selenium Grid Extras 2.x, I had re-generated all my node configurations.
And it was working fine up to today...

**Comment by bjharo** [comment]
I'm encountering this as well.  I think a change in Selenium 3.9 or 3.9.1 broke Extras compatibility.  Here's the error I'm seeing on my hub when a node tries to register.

`2018-02-12 11:06:58.855:WARN:osjs.HttpChannel:qtp205962452-19: /grid/register
java.security.InvalidParameterException: Error: com.groupon.seleniumgridextras.grid.proxies.SetupTeardownProxy
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:375)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:71)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Thread.java:745)`

If change the proxy on my node config to the standard one, "org.openqa.grid.selenium.proxy.DefaultRemoteProxy", instead of the Extras one, my node will successfully register and I can run tests.

**Comment by vlemaitre** [comment]
Thanks for your answer, I will try that.
But what is the difference between these 2 proxy ?
What feature I will loose ?

Thanks and Regards

**Comment by nkalgin** [comment]
I already try use DefaultRemoteProxy - it registered well, but in my case(issue 389) - browser session didn't opened

**Comment by bjharo** [comment]
@vlemaitre I'm not entirely sure what features are lost.  All I know is that the proxy I switched to is the one normally used by Selenium Grid when you are not using Extras.

**Comment by therippa** [comment]
Chiming in my experience after messing around with this for the last few hours - anything past Selenium 3.7.1 will not register with the hub

**Comment by nkalgin** [comment]
3.7.1 on both sides solves the problem

**Comment by smccarthy** [comment]
Sorry its taking so long for me to look at this issue. I am not really involved with this project (time limitations). It is odd because version 2 of selenium-grid-extras was only created to support selenium 3.7.1 (and I thought newer). I will try some debugging today... maybe the selenium project reverted the change that required us to jump to selenium-grid-extras 2.

**Comment by smccarthy** [comment]
I did some researching, and when my hub is 3.8.1 , nodes can connect (even a 3.9.1 node). However, if my hub is 3.9.0 , nodes can not attach. Can someone else verify if that's the case for them too ? I will see if I can spot anything in the selenium commits from after 3.8.1 --> 3.9.0 that looks suspicious.

**Comment by smccarthy** [comment]
@bjharo How did you get that stacktrace? Did it tell you what inside of `SetupTeardownProxy` was causing the issue?

**Comment by vlemaitre** [comment]
1/ If I use the DefaultRemoteProxy it works.
I just try the SetupTeardownProxy with a hub 3.8.1 and a node 3.9.1 and it works too.
With a hub 3.9.0 it crashes.
It seems the issue comes with the hub version 3.9.0.
Thanks for your help.

**Comment by smccarthy** [comment]
I talked with the selenium team, and this issue was related to https://github.com/SeleniumHQ/selenium/commit/65fe98162e154afc5cb3eee51a1cb24a4781ccd3 . We can add a `@ManagedService(description = "Selenium-Grid-Extras SetupTeardownProxy")` annotation above our `SetupTeardownProxy` which solves it. The commit above will be in selenium 3.10 as well (so we shouldn't need it after that). I'll do some more testing today with the annotation and if it all works out, I'll publish a release tonight.

@vlemaitre @bjharo @nkalgin @therippa

**Comment by smccarthy** [comment]
Please try out 2.0.2 : https://github.com/groupon/Selenium-Grid-Extras/releases/tag/v2.0.2 . Once someone responds that its fixed for them, I will close this issue. I tried out a simple test with 3.7.1 and 3.9.1 and both worked.

**Comment by therippa** [comment]
@smccarthy - 2.0.2 is working for me with 3.9.1, thanks!

**Comment by vlemaitre** [comment]
Thanks a lot, it works well.
