### ISSUE TITLE
Unable to register a node on the latest version

### ISSUE THREAD

**Issue by sdarshanam** [groupon/Selenium-Grid-Extras#404]
Hub : Linux 
Node : Windows 8
Started the Hub and its running fine.
Started the Node as per the instructions provided.
See the following error message and the node does not get started.
`
C:\Users\Administrator\Downloads\selenium>java -Dwebdriver.ie.driver=\tmp\webdri
ver\iedriver\iedriver_3.12.0_x64bit.exe -Dwebdriver.edge.driver="C:\Program File
s (x86)\Microsoft Web Driver\MicrosoftWebDriver.exe" -Dwebdriver.chrome.driver=\
tmp\webdriver\chromedriver\chromedriver_2.38_32bit.exe -Dwebdriver.gecko.driver=
\tmp\webdriver\geckodriver\geckodriver_0.20.1.exe -cp C:\Users\Administrator\Dow
nloads\selenium\SeleniumGridExtras-2.0.4-SNAPSHOT-jar-with-dependencies.jar;\tmp
\webdriver\3.12.0.jar org.openqa.grid.selenium.GridLauncherV3 -role node -nodeCo
nfig node_5555.json -log log\node_5555.log
Exception in thread "main" org.openqa.grid.common.exception.GridConfigurationExc
eption: Error with the JSON of the config : Expected value to be a string type:
NUMBER
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.9
36Z'
System info: host: 'WIN-AHNG9735N3J', ip: '10.79.200.41', os.name: 'Windows Serv
er 2012', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_171'
Driver info: driver.version: unknown
        at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.lo
adFromJSON(GridNodeConfiguration.java:407)
        at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.lo
adFromJSON(GridNodeConfiguration.java:387)
        at org.openqa.grid.internal.cli.GridNodeCliOptions.toConfiguration(GridN
odeCliOptions.java:205)
        at org.openqa.grid.internal.cli.GridNodeCliOptions.toConfiguration(GridN
odeCliOptions.java:34)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:11
5)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:82)
Caused by: org.openqa.grid.common.exception.GridConfigurationException: Expected
 value to be a string type: NUMBER
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.9
36Z'
System info: host: 'WIN-AHNG9735N3J', ip: '10.79.200.41', os.name: 'Windows Serv
er 2012', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_171'
Driver info: driver.version: unknown
        at org.openqa.grid.internal.utils.configuration.StandaloneConfiguration.
loadFromJson(StandaloneConfiguration.java:179)
        at org.openqa.grid.internal.utils.configuration.GridNodeConfiguration.lo
adFromJSON(GridNodeConfiguration.java:392)
        ... 5 more
Caused by: org.openqa.selenium.json.JsonException: Expected value to be a string
 type: NUMBER
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:08.9
36Z'
System info: host: 'WIN-AHNG9735N3J', ip: '10.79.200.41', os.name: 'Windows Serv
er 2012', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_171'
Driver info: driver.version: unknown
        at org.openqa.selenium.json.StringCoercer.lambda$apply$0(StringCoercer.j
ava:41)
        at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoerce
r.java:142)
        at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:
122)
        at org.openqa.selenium.json.MapCoercer.lambda$null$0(MapCoercer.java:68)`

**Comment by mayurjurani** [comment]
Same issue found on windows node as well

**Comment by Andro72** [comment]
It is because it is used \tmp \webdriver\3.12.0.jar 
WARNING: Selenium 3.7.1 is the oldest compatible version with Selenium-Grid-Extras 2.x. Downgrade to Selenium-Grid-Extras 1.x if you would like to use an older version of webdriver.
In selenium_grid_extras_config.json

    "auto_update_drivers": "0",
    "webdriver": {
      "version": "3.7.1"
    },

**Comment by mayurjurani** [comment]
3.12.0 is higher version than 3.7.1
`"auto_update_drivers": "1",
"webdriver": {
  "version": "3.12.0"
},`
should be valid configuration since driver version 3.11.0 works absolutely fine.

**Comment by jegeary** [comment]
I am having the same issue. I had to edit my config to not auto update the webdriver and set it to 3.11.0 and I could get the node up and running after restarting the Hub.

**Comment by vlemaitre** [comment]
I face the same issue since moving on driver 3.12.0.
Staying on 3.11.0 is ok.

**Comment by gwynjudd** [comment]
I changed the following to get it working (was 3.12.0):

```
    "auto_update_drivers": "0",
    "webdriver": {
      "version": "3.11.0"
    },
```

**Comment by shankarkc** [comment]
it looks like its because of https://github.com/SeleniumHQ/selenium/issues/6275

**Comment by shankarkc** [comment]
It looks like there are other bugs too to use latest selenium. I modified the code to remove the custom section. I still see extra proxy having issues. Just by removing custom grid extra will not work😥
