### ISSUE TITLE
LOG level

### ISSUE THREAD

**Issue by mstankovic86** [groupon/Selenium-Grid-Extras#85]
I just noticed that my log files are too big (over 8GB per day). Would be nice if I could set log level to ERROR for example.

**Comment by smccarthy** [comment]
@mstankovic86 It looks like the node_5555.log is the one that is the largest (for me). Followed by the grid_hub.log. These logs are generated by selenium, not by selenium_grid_extras. Still coming up with a solution, but wanted to point it out.

**Comment by mstankovic86** [comment]
Not for me.

![screen shot 2015-01-22 at 12 12 22 pm](https://cloud.githubusercontent.com/assets/8803779/5897901/ea66b5f6-a549-11e4-9005-10513188e38c.png)

**Comment by smccarthy** [comment]
Ok. This helps @mstankovic86 . Thanks. I am still looking into this issue.

**Comment by cktech529** [comment]
I'm seeing similar behavior with the node_5555.log file (@ 5GB+)

**Comment by smccarthy** [comment]
@cktech529 @mstankovic86 I have been looking at this issue yesterday and today, and I have two solutions (for the grid_extras.log , not the node or hub logs yet).

1) Comment out line 65 : https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/SeleniumGridExtras.java#L65 and rebuild. Than create your own log4j.properties (can copy https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/resources/log4j.properties) file and place it in the same directory as your jar file and start the service like : java -Dlog4j.debug -Dlog4j.configuration=file:log4j.properties -jar SeleniumGridExtras-1.7.1-SNAPSHOT-jar-with-dependencies.jar

2) As is (no code changes), create a log4j.properties in the same directory as your jar file. Start the service like : java -Dlog4j.debug -Dlog4j.configuration=file:log4j.properties -cp .:SeleniumGridExtras-1.7.1-SNAPSHOT-jar-with-dependencies.jar com.groupon.seleniumgridextras.SeleniumGridExtras (this is for a Mac. Might be slightly different for Windows. I think Windows uses semi-colons instead of colons so split out the classpath.).

I am not great with logging, so I don't know what commenting out the PropertyConfigurator.configure() line will affect. 

Please let me know if this works for you! You can also still use java -jar SeleniumGridExtras-1.7.1-SNAPSHOT-jar-with-dependencies.jar , and it will use the log4j.properties included in the jar file (this one : https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/resources/log4j.properties ).

**Comment by smccarthy** [comment]
For the selenium hub and node logging, try to put this in the selenium_grid_extras_config.json :

    "grid_jvm_options": {
      "selenium.LOGGER.level": "WARNING"
    },

Replace WARNING with any of the java.util.logging Levels : http://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html

Please let me know if these two solutions work for you. Thank you!

**Comment by mstankovic86** [comment]
@smccarthy second solution works for me. Thanks, but I still have a problem with grid_extras.log.

**Comment by smccarthy** [comment]
@mstankovic86 Can you confirm you used this command to start the Grid Extras jar file : 
java -Dlog4j.debug -Dlog4j.configuration=file:log4j.properties -cp .:SeleniumGridExtras-1.7.1-SNAPSHOT-jar-with-dependencies.jar com.groupon.seleniumgridextras.SeleniumGridExtras
?

If so, can you paste the log4j.properties file you are using (should be in the same directory as the jar) here?

Thanks !

**Comment by mstankovic86** [comment]
I got this error:

[build@master-ts seleniumGridExtras]$ log4j:ERROR Could not instantiate class [org.apache.log4j.rolling.RollingFileAppender].
java.lang.ClassNotFoundException: org.apache.log4j.rolling.RollingFileAppender
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:188)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:178)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:319)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:120)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:629)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:612)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:509)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:415)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:441)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:470)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at com.groupon.seleniumgridextras.SeleniumGridExtras.<clinit>(SeleniumGridExtras.java:61)
log4j:ERROR Could not instantiate appender named "FILE".
log4j:ERROR Could not instantiate class [org.apache.log4j.rolling.RollingFileAppender].
java.lang.ClassNotFoundException: org.apache.log4j.rolling.RollingFileAppender
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:188)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:178)
	at org.apache.log4j.helpers.OptionConverter.instantiateByClassName(OptionConverter.java:319)
	at org.apache.log4j.helpers.OptionConverter.instantiateByKey(OptionConverter.java:120)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:629)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:612)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:509)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:415)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:441)
	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:336)
	at com.groupon.seleniumgridextras.SeleniumGridExtras.main(SeleniumGridExtras.java:65)
log4j:ERROR Could not instantiate appender named "FILE".


my log4j.properties file:

# Define the root logger with appender file
log = log/
log4j.rootLogger = ERROR, FILE

# Define the file appender
log4j.appender.FILE=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.FILE.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
log4j.appender.FILE.rollingPolicy.FileNamePattern=${log}/grid_extras.%d{yyyy-MM-dd}.log

# Define the layout for file appender
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} [%t] %-5p %c{2} %x - %m%n


script for starting SGE:

java -Dlog4j.debug -Dlog4j.configuration=file:log4j.properties -cp .:SeleniumGridExtras-1.7.1.jar com.groupon.seleniumgridextras.SeleniumGridExtras

NOTE: log4j and sge.jar are in the same directory

**Comment by smccarthy** [comment]
@mstankovic86 Is this still an issue with SeleniumGridExtras 1.10.0 ? I can try it again as well sometime this week.

**Comment by mstankovic86** [comment]
@smccarthy I don't have this problem with SeleniumGridExtras 1.10.0. (for nodes) 

P.S. for hub, I reduced my log file with: 

"grid_jvm_options": {
  "selenium.LOGGER.level": "SEVERE"
},

**Comment by smccarthy** [comment]
@mstankovic86 Sorry I meant for the grid_extras.log . You mentioned before that the solution for the grid_extras.log gave you an error. The solution was to use this as the command to start the grid extras jar :
java -Dlog4j.debug -Dlog4j.configuration=file:log4j.properties -cp .:SeleniumGridExtras-1.7.1.jar com.groupon.seleniumgridextras.SeleniumGridExtras (assumes linux or mac, not windows because of the : instead of ;).

**Comment by mstankovic86** [comment]
@smccarthy my previous comment is updated. You can resolve this issue.

**Comment by smccarthy** [comment]
Thank you! Closing this issue.
